#!bin/sh
#
# Using Digital Raccoon as the theme.
# Requires jq

THEME_FILE="digital-raccoon.json"

export THEME_MAIN_COLOR=$(cat $THEME_FILE | jq '.blue' -r)
export THEME_BRIGHT_COLOR=$(cat $THEME_FILE | jq '.brightBlue' -r)
export THEME_COMPLIMENTARY_COLOR=$(cat $THEME_FILE | jq '.red' -r)
export THEME_HIGHLIGHT_COLOR=$(cat $THEME_FILE | jq '.brightRed' -r)
export THEME_NEUTRAL_COLOR=$(cat $THEME_FILE | jq '.foreground' -r)

export GUM_CHOOSE_SELECTED_FOREGROUND=$THEME_COMPLIMENTARY_COLOR
export GUM_CHOOSE_ITEM_FOREGROUND=$THEME_MAIN_COLOR
export GUM_CHOOSE_HEADER_FOREGROUND=$THEME_MAIN_COLOR
export GUM_CHOOSE_CURSOR_FOREGROUND=$THEME_COMPLIMENTARY_COLOR

export GUM_CONFIRM_PROMPT_FOREGROUND=$THEME_HIGHLIGHT_COLOR
export GUM_CONFIRM_SELECTED_BACKGROUND=$THEME_MAIN_COLOR
export GUM_CONFIRM_SELECTED_FOREGROUND=$THEME_HIGHLIGHT_COLOR
export GUM_CONFIRM_UNSELECTED_FOREGROUND=$THEME_HIGHLIGHT_COLOR

